# Generated by Django 4.1 on 2025-09-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcuerdoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerador', models.PositiveIntegerField()),
                ('unidad', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')])),
                ('acuerdo', models.TextField()),
                ('unidad_parada', models.BooleanField(default=False)),
                ('fecha_limite', models.DateField()),
                ('pendiente', models.BooleanField(default=True)),
                ('porcentaje_avance', models.PositiveSmallIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuerdos', to='operativo.integrante')),
            ],
        ),
    ]
