# Generated by Django 4.1 on 2025-09-26 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0002_acuerdooperativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartado', models.CharField(choices=[('produccion', 'Producción'), ('mantenimiento', 'Mantenimiento'), ('seguridad', 'Seguridad y Ambiental'), ('superintendencia', 'Superintendencia General')], max_length=50)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
