# Generated by Django 4.1 on 2025-09-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0003_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
