# Generated by Django 4.1 on 2025-10-03 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0004_alter_nota_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioAcuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
                ('acuerdo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='operativo.acuerdooperativo')),
            ],
        ),
    ]
