# Generated by Django 4.1 on 2025-10-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaDirectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartado', models.CharField(choices=[('produccion', 'Producción'), ('mantenimiento', 'Mantenimiento'), ('gestion', 'Gestión de Recursos'), ('seguridad', 'Seguridad, Ambiental y Calidad'), ('superintendencia', 'Superintendencia General')], max_length=50)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
