# Generated by Django 4.1 on 2025-10-06 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directivo', '0002_notadirectivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioDirectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('acuerdo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='directivo.acuerdodirectivo')),
            ],
        ),
    ]
